#!/usr/bin/env bash

# Enable Bash bash_completion
if [[ -f /usr/share/bash-completion/bash_completion ]]; then
  source /usr/share/bash-completion/bash_completion
elif [[ -f /etc/bash_completion ]]; then
  source /etc/bash_completion
fi
bind "set completion-ignore-case on" 2>/dev/null
bind "set show-all-if-ambiguous on" 2>/dev/null

shopt -s autocd

source ~/.variables
source ~/.aliases
source ~/.functions

if command -v fzf >/dev/null 2>&1; then
  source <(fzf --bash)
fi

if command -v starship >/dev/null 2>&1; then
  eval "$(starship init bash)"
fi

if command -v hugo >/dev/null 2>&1; then
  source <(hugo completion bash)
fi
