return {
  {
    "hrabid/matugen.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      load_theme = true,

      -- Path to the JSONC file generated by matugen
      jsonc_path = vim.fn.expand("~/.config/nvim/nvim-colors.jsonc"),
    },
  },
}
