#!/usr/share/env bash

if command -v sudo &>/dev/null; then
  echo "Installing with sudo......."
  sudo dnf install git zsh lsd bat tmux unzip fzf neovim vim unzip fastfetch btop htop pass gnupg w3m aerc glow jq -y
  curl -sS https://starship.rs/install.sh | sh
else
  echo "Installing without sudo......."
  dnf install git zsh lsd bat tmux unzip fzf neovim vim unzip fastfetch btop htop pass gnupg w3m aerc glow jq -y
  curl -sS https://starship.rs/install.sh | sh

