APP_CONFIG_VER = 2
APP_FLATPAK = y
APP_APPIMAGE = y
APP_YAY = y
APP_PARU = y
APP_SNAP = n
APP_APT = y
APP_DNF = y
APP_PACMAN = y
APP_ZYPPER = y
APP_NIXENV = y
APP_BREW = y
APP_GOLANG = y
APP_PIP = y
APP_CARGO = y
